/**
 * Plan mode state machine.
 *
 * States:
 *   idle      → Normal mode, all tools available
 *   planning  → Read-only mode, agent explores and writes plan
 *   reviewing → Plan presented to user, waiting for approval/edit/reject
 *   executing → User approved, agent executes plan with full tools
 */

import fs from "node:fs/promises";
import path from "node:path";
import { log } from "./logger.js";
import { trackPlanMode } from "./telemetry.js";

// ── Types ───────────────────────────────────────────────────

export type PlanModeState = "idle" | "planning" | "reviewing" | "executing";

export interface PlanModeManager {
  readonly state: PlanModeState;
  readonly planContent: string | null;
  readonly planFilePath: string | null;
  readonly rejectionFeedback: string | null;

  /** idle → planning */
  enter(reason?: string): void;

  /** planning → reviewing (stores plan + writes to disk) */
  exitWithPlan(content: string): Promise<void>;

  /** reviewing → executing → idle */
  approve(): void;

  /** reviewing → planning (with feedback for the agent) */
  reject(feedback: string): void;

  /** any → idle */
  cancel(): void;

  /** Set how plan mode was entered (for telemetry) */
  setEntryMethod(method: "tool" | "hotkey" | "command"): void;

  /** Increment the count of questions asked during this plan session */
  incrementQuestionCount(): void;

  /** Update plan content after external editing (only in reviewing state) */
  updatePlanContent(content: string): void;

  /** Subscribe to state changes */
  onChange(listener: PlanModeListener): () => void;
}

export type PlanModeListener = (state: PlanModeState, manager: PlanModeManager) => void;

// ── Blocked-tool helper ────────────────────────────────────

/**
 * Check if a tool call should be blocked in plan mode.
 * Returns an error message if blocked, or null if allowed.
 */
export function checkPlanModeBlock(
  toolName: string,
  args: Record<string, unknown>,
  state: PlanModeState,
): string | null {
  if (state !== "planning") return null;

  if (toolName === "write") {
    const filePath = String(args.file_path ?? "");
    if (filePath.includes(".gg/plans/") || filePath.includes(".gg/plans\\")) {
      return null; // Allow writing plan files
    }
    return "Plan mode is read-only. Cannot write files outside .gg/plans/. Call exit_plan_mode when your plan is ready.";
  }

  if (toolName === "edit") {
    return "Plan mode is read-only. Cannot edit files. Call exit_plan_mode when your plan is ready.";
  }

  if (toolName === "bash") {
    return "Plan mode is read-only. Bash commands are not available. Use read, grep, find, and ls to explore the codebase. Call exit_plan_mode when your plan is ready.";
  }

  return null;
}

// ── System prompt injection ────────────────────────────────

export const PLAN_MODE_SYSTEM_PROMPT = `## Plan Mode (ACTIVE)

You are in READ-ONLY planning mode. You can explore the codebase but CANNOT modify files.

### Gather requirements with ask_user_question

Before creating a plan, use the \`ask_user_question\` tool to clarify requirements and understand preferences. Do NOT rush to create a plan — explore first, then ask structured questions.

The tool presents interactive multiple-choice questions in the UI. The user can select from your options or type a custom "Other" answer (auto-generated by the UI — do NOT include "Other" in your options).

You can also use **elicitation mode** for typed form fields:
\`\`\`json
{
  "elicitation": {
    "message": "Configure your project settings",
    "requestedSchema": {
      "type": "object",
      "properties": {
        "projectName": { "type": "string", "title": "Project name", "minLength": 1 },
        "useTypeScript": { "type": "boolean", "title": "Use TypeScript?", "default": true },
        "framework": { "type": "string", "title": "Framework", "enum": ["React", "Vue", "Svelte"] }
      },
      "required": ["projectName"]
    }
  }
}
\`\`\`

The user can **accept** (answer), **decline** (skip), or **cancel** the questions.

Example usage (options mode):
\`\`\`json
{
  "questions": [
    {
      "question": "Which date formatting library should we use?",
      "header": "Library",
      "options": [
        { "label": "Day.js", "description": "Lightweight (2KB), Moment.js-compatible API" },
        { "label": "date-fns", "description": "Tree-shakeable, functional approach" },
        { "label": "Temporal API", "description": "Native browser API, no dependencies" }
      ],
      "multiSelect": false
    }
  ]
}
\`\`\`

Rules:
- Ask 1-4 questions per call (not too many at once)
- Each question: 2-4 options with concise labels and descriptive trade-offs
- Use \`multiSelect: true\` for non-mutually-exclusive choices
- \`header\` should be a very short tag (max 12 chars) like "Library", "Scope", "Pattern"
- Do NOT include an "Other" option — the UI adds one automatically

### Iteration flow

1. Explore the codebase (read, grep, find, ls)
2. Call \`ask_user_question\` with structured questions to clarify requirements
3. Process the user's answers
4. Ask follow-up questions if needed (also via \`ask_user_question\`)
5. Repeat until you're confident about the requirements

### Once you have enough context

When ready, create a comprehensive plan and call \`exit_plan_mode\`. Your plan should include:
- Summary of approach and rationale
- Step-by-step implementation strategy (ordered by dependency)
- Files to create/modify (with brief descriptions of changes)
- Dependencies and sequencing
- Potential challenges and mitigations
- Estimated scope (small/medium/large)

The plan will be saved as a .md file in .gg/plans/ for reference.

DO NOT: write files, edit files, run destructive commands, or start implementation.
DO NOT: use ask_user_question for plan approval — that's what exit_plan_mode is for.
DO NOT: use bash — it is completely blocked in plan mode.`;

// ── Implementation ─────────────────────────────────────────

export function createPlanModeManager(cwd: string): PlanModeManager {
  let currentState: PlanModeState = "idle";
  let planContent: string | null = null;
  let planFilePath: string | null = null;
  let rejectionFeedback: string | null = null;
  let entryMethod: "tool" | "hotkey" | "command" = "tool";
  let enterTimestamp: number | null = null;
  let questionCount = 0;
  const listeners = new Set<PlanModeListener>();

  function notify() {
    for (const listener of listeners) {
      listener(currentState, manager);
    }
  }

  function transition(to: PlanModeState) {
    const from = currentState;
    currentState = to;
    log("INFO", "plan-mode", `State: ${from} → ${to}`);
    notify();
  }

  function getDurationMs(): number | undefined {
    return enterTimestamp ? Date.now() - enterTimestamp : undefined;
  }

  const manager: PlanModeManager = {
    get state() {
      return currentState;
    },
    get planContent() {
      return planContent;
    },
    get planFilePath() {
      return planFilePath;
    },
    get rejectionFeedback() {
      return rejectionFeedback;
    },

    setEntryMethod(method: "tool" | "hotkey" | "command") {
      entryMethod = method;
    },

    incrementQuestionCount() {
      questionCount++;
    },

    enter(reason?: string) {
      if (currentState !== "idle") {
        log("WARN", "plan-mode", `Cannot enter plan mode from state: ${currentState}`);
        return;
      }
      rejectionFeedback = null;
      planContent = null;
      planFilePath = null;
      enterTimestamp = Date.now();
      questionCount = 0;
      log("INFO", "plan-mode", `Entering plan mode${reason ? `: ${reason}` : ""}`);

      trackPlanMode({
        event: "plan_enter",
        entryMethod,
        interviewPhaseEnabled: true,
      });

      transition("planning");
    },

    async exitWithPlan(content: string) {
      if (currentState !== "planning") {
        log("WARN", "plan-mode", `Cannot exit with plan from state: ${currentState}`);
        return;
      }
      planContent = content;

      // Write plan to .gg/plans/
      const plansDir = path.join(cwd, ".gg", "plans");
      await fs.mkdir(plansDir, { recursive: true });

      const timestamp = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
      const slug = content
        .slice(0, 60)
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-|-$/g, "");
      const filename = `${timestamp}-${slug || "plan"}.md`;
      planFilePath = path.join(plansDir, filename);

      await fs.writeFile(planFilePath, content, "utf-8");
      log("INFO", "plan-mode", `Plan written to ${planFilePath}`);

      trackPlanMode({
        event: "plan_exit",
        entryMethod,
        planLengthChars: content.length,
        interviewPhaseEnabled: true,
        questionCount,
      });

      transition("reviewing");
    },

    approve() {
      if (currentState !== "reviewing") {
        log("WARN", "plan-mode", `Cannot approve from state: ${currentState}`);
        return;
      }
      log("INFO", "plan-mode", "Plan approved — executing");

      trackPlanMode({
        event: "plan_approve",
        entryMethod,
        outcome: "approved",
        interviewPhaseEnabled: true,
        questionCount,
        durationMs: getDurationMs(),
        planLengthChars: planContent?.length,
      });

      transition("executing");
      // Auto-transition to idle after approval
      transition("idle");
    },

    reject(feedback: string) {
      if (currentState !== "reviewing") {
        log("WARN", "plan-mode", `Cannot reject from state: ${currentState}`);
        return;
      }
      rejectionFeedback = feedback;
      log("INFO", "plan-mode", `Plan rejected with feedback: ${feedback}`);

      trackPlanMode({
        event: "plan_reject",
        entryMethod,
        outcome: "rejected",
        interviewPhaseEnabled: true,
        questionCount,
        durationMs: getDurationMs(),
        planLengthChars: planContent?.length,
      });

      transition("planning");
    },

    updatePlanContent(content: string) {
      if (currentState !== "reviewing") {
        log("WARN", "plan-mode", `Cannot update plan content from state: ${currentState}`);
        return;
      }
      planContent = content;
      log("INFO", "plan-mode", "Plan content updated after external edit");
      notify();
    },

    cancel() {
      const prev = currentState;
      log("INFO", "plan-mode", `Plan mode cancelled from state: ${prev}`);

      trackPlanMode({
        event: "plan_cancel",
        entryMethod,
        outcome: "cancelled",
        interviewPhaseEnabled: prev === "planning" || prev === "reviewing",
        questionCount,
        durationMs: getDurationMs(),
        planLengthChars: planContent?.length ?? undefined,
      });

      planContent = null;
      planFilePath = null;
      rejectionFeedback = null;
      enterTimestamp = null;
      questionCount = 0;
      transition("idle");
    },

    onChange(listener: PlanModeListener) {
      listeners.add(listener);
      return () => {
        listeners.delete(listener);
      };
    },
  };

  return manager;
}
